meta:
  environment: docker
  toolchain: dockerfile

services:
  trudnik-app:
    build:
      dockerfile: Dockerfile
    run:
      containerPort: 8000
      persistenceMount: /data
    environment:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      DEPLOYMENT_ENV: production
      POSTGREST_URL: ${POSTGREST_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: ${REDIS_URL}

  trudnik-celery:
    build:
      dockerfile: Dockerfile
    run:
      command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      DEPLOYMENT_ENV: production
      POSTGREST_URL: ${POSTGREST_URL}
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
