meta:
  environment: docker
  toolchain: dockerfile

services:
  trudnik-app:
    build:
      dockerfile: Dockerfile
    run:
      containerPort: 80
      persistenceMount: /data
    environment:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      DEPLOYMENT_ENV: production
      POSTGREST_URL: http://amvera-hyperstls-run-trudnik-pr:3000

  trudnik-celery:
    build:
      dockerfile: Dockerfile
    run:
      command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      DEPLOYMENT_ENV: production
      POSTGREST_URL: http://amvera-hyperstls-run-trudnik-pr:3000
