-- ============================================================
-- Disclaimer: public.spatial_ref_sys — системная таблица PostGIS
-- (справочник систем координат). Владелец таблицы — postgres/ext.
-- Пользователь без прав владельца НЕ может изменить её (`ERROR 42501`).
-- Включение RLS невозможно без владения таблицей.
--
-- Решение: подавить предупреждение вручную в Supabase Dashboard:
--   1. Database → Linter
--   2. Найти "rls_disabled_in_public — public.spatial_ref_sys"
--   3. Нажать "Dismiss"
--
-- Альтернативно (только от superuser/postgres):
--   ALTER TABLE public.spatial_ref_sys OWNER TO postgres;
--   ALTER TABLE public.spatial_ref_sys ENABLE ROW LEVEL SECURITY;
--   CREATE POLICY "spatial_ref_sys_select" ON public.spatial_ref_sys
--       FOR SELECT USING (true);
--
-- ============================================================
-- Почему это безопасно (обоснование для dismiss):
--   • Таблица содержит только read-only справочные данные (SRID-коды)
--   • PostGIS функции используют владельца (postgres), который обходит RLS
--   • Приложение не обращается к spatial_ref_sys через PostgREST API
--   • Это стандартный false-positive для PostGIS в Supabase
