-- Миграция 030: Закрытие пробелов схемы БД (сверка 13.06.2026)

-- 1. Уникальный индекс для предотвращения двойной оплаты (из 029 — не был применён)
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_payments_paid_unique 
ON job_payments (job_id) WHERE status = 'paid';

-- 2. INSERT-политика для notifications (сервис использует service_role, но политика нужна)
DROP POLICY IF EXISTS "Service can insert notifications" ON notifications;
CREATE POLICY "Service can insert notifications" ON notifications 
FOR INSERT WITH CHECK (true);

-- 3. UPDATE-политика для job_payments
DROP POLICY IF EXISTS "Users can update own job payments" ON job_payments;
CREATE POLICY "Users can update own job payments" ON job_payments 
FOR UPDATE USING (auth.uid() = employer_id);

-- 4. INSERT/UPDATE/DELETE политики для skills (админ)
DROP POLICY IF EXISTS "Admin can insert skills" ON skills;
CREATE POLICY "Admin can insert skills" ON skills FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admin can update skills" ON skills;
CREATE POLICY "Admin can update skills" ON skills FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Admin can delete skills" ON skills;
CREATE POLICY "Admin can delete skills" ON skills FOR DELETE USING (true);

-- 5. INSERT/UPDATE/DELETE политики для religions (админ)
DROP POLICY IF EXISTS "Admin can insert religions" ON religions;
CREATE POLICY "Admin can insert religions" ON religions FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admin can update religions" ON religions;
CREATE POLICY "Admin can update religions" ON religions FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Admin can delete religions" ON religions;
CREATE POLICY "Admin can delete religions" ON religions FOR DELETE USING (true);

-- 6. Удалить дублирующую колонку read (есть is_read)
ALTER TABLE notifications DROP COLUMN IF EXISTS read;

-- 7. CREATE TABLE IF NOT EXISTS для таблиц без миграций (воспроизводимость)
-- (Схемы приблизительные — точные соответствуют реальной БД из supabase_schema.json)

CREATE TABLE IF NOT EXISTS applications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    worker_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','withdrawn')),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(job_id, worker_id)
);

CREATE TABLE IF NOT EXISTS blacklists (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    blocked_user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(user_id, blocked_user_id)
);

CREATE TABLE IF NOT EXISTS favorites (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    target_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(user_id, target_id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    employer_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title varchar(255) NOT NULL,
    description text NOT NULL DEFAULT '',
    address varchar(500),
    salary varchar(100),
    status varchar(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','active','completed','cancelled')),
    max_workers integer DEFAULT 1,
    tariff varchar(20) DEFAULT 'standard',
    is_paid boolean DEFAULT false,
    paid_at timestamptz,
    expires_at timestamptz,
    preferred_religion uuid REFERENCES religions(id),
    search_vector tsvector,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS messages (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    application_id uuid REFERENCES applications(id) ON DELETE SET NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS job_favorites (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(user_id, job_id)
);

CREATE TABLE IF NOT EXISTS job_photos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    url text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employer_details (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
    company_name varchar(255),
    inn varchar(12),
    is_self_employed boolean DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
